services:
  - type: web
    name: mokammel-backend
    runtime: image
    repo: https://github.com/noroncomputer-dev/mokammel-backend
    branch: main
    rootDir: server
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 8080
      - key: MONGODB_URI
        value: mongodb+srv://noroncomputer_db_user:mfVXbPvocluMnbF7@mokammel.n73n723.mongodb.net/mokammel?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: supersecret
      - key: NODE_ENV
        value: production
